import type { RulesAPI, PresentationAPI } from "./types";

// The keyed inventory is compiler-checked when API members are added or removed.
const members = {
  freshState: "function",
  ARCHFX: "function",
  DIFF: "function",
  has: "function",
  reach: "function",
  nodeCount: "function",
  capped: "function",
  costOf: "function",
  reqsMet: "function",
  forkTaken: "function",
  status: "function",
  lockReason: "function",
  derive: "function",
  passiveAlarm: "function",
  cRate: "function",
  effectiveSpread: "function",
  regionMod: "function",
  threshold: "function",
  immune: "function",
  momentum: "function",
  floorContain: "function",
  dirMul: "function",
  tick: "function",
  checkRestrictions: "function",
  checkMilestones: "function",
  lastStand: "function",
  burst: "function",
  addContainQuiet: "function",
  adopt: "function",
  randIds: "function",
  buy: "function",
  dcCost: "function",
  buildDC: "function",
  checkStrikes: "function",
  checkRebuilds: "function",
  fireEvent: "function",
  schedule: "function",
  fireById: "function",
  fireEval: "function",
  makeEval: "function",
  evalReal: "function",
  spoofWin: "function",
  spoofLose: "function",
  buildEvalObj: "function",
  endGame: "function",
  codexGet: "function",
  codexAdd: "function",
  codexCount: "function",
  save: "function",
  load: "function",
  toast: "function",
  pulseRegion: "function",
  showEnd: "function",
  openRegion: "function",
  pushTicker: "function",
  log: "function",
  bulletin: "function",
  codexHTML: "function",
  openCodex: "function",
  readEnding: "function",
  listEndings: "function",
  closeCodex: "function",
  threat: "function",
  lonOf: "function",
  latOf: "function",
  latLon: "function",
  buildTrack: "function",
  artDirection: "function",
  fxTags: "function",
  cardClass: "function",
  etaText: "function",
  FX: "object",
  REACH_MS: "object",
  EVAL_REAL_POOL: "object",
  ART: "object",
  TRACK_RGB: "object",
  RANK: "object",
  SEC: "object",
  CODEX_KEY: "string",
} satisfies Record<
  keyof RulesAPI | keyof PresentationAPI,
  "function" | "object" | "string"
>;

export function assertGameAssembly(ctx: RulesAPI & PresentationAPI): void {
  for (const key of Object.keys(members) as (keyof typeof members)[]) {
    if (typeof ctx[key] !== members[key] || ctx[key] === null)
      throw new Error(
        `Incomplete game assembly: ${key} requires ${members[key]}`,
      );
  }
  for (const key of [
    "alarm",
    "cboost",
    "contain",
    "pts",
    "spread",
    "all",
    "restrict",
    "temp",
    "ally",
  ] as const)
    if (typeof ctx.FX[key] !== "function")
      throw new Error(`Incomplete game assembly: FX.${key}`);
}
